---
title: "Final Project Proposal "
author: "Han Wang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Proposal Descriptions

## About Dataset

**Data:** The data I am going to use in my final project is called **Online Retail Data Set** from UCI ML repo. Here's the link for the dataset: <https://archive.ics.uci.edu/ml/datasets/online+retail>

**Source:** Dr Daqing Chen, Director: Public Analytics group. chend '\@' lsbu.ac.uk, School of Engineering, London South Bank University, London SE1 0AA, UK.

**Information:** This is a transnational data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.The company mainly sells unique all-occasion gifts. Many customers of the company are wholesalers.

## Modeling Goal

Through this project, I would like to learn how `sales` will differ based on `month`, `week`, `time`, `unit price` and `quantity`. I will use three models to predict the sales, ranging from the least interpretable one(Random Forest) to the most(Logistic Regression). By evaluating the accuracy of each model, this project will answer the following questions:

-   Do the models have concurrent or conflicting interpretations? Can you explain why?

-   Do some models offer more insight than others?

-   Is it worth losing interpretability/increasing model complexity? Can the simpler model do just as well? Why or why not?

-   To what extent is it possible to answer your questions of interest with the models you have chosen? What are their limitations?

## Methods

1.  Random Forest Regression
2.  K-means Regression
3.  Logistic Regression
