# [Model 2] Tree Regression

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
library(rpart)

data <- read.csv('online_retail_cleaned_adjusted.csv')
# str(data)
```

```{r}
# train test split
set.seed(111)
ind <- sample(2, nrow(data), replace = TRUE, prob = c(0.75, 0.25))
trainset<- data[ind==1, ]
trainset <- subset(trainset, select = -X)
testset <- data[ind==2, ]
testset <- subset(testset, select = -X)
```

```{r}
# Perform Regression Tree
library(rpart.plot)
dt <- rpart(Sales~., method = 'anova',
            control = list(minsplit = 10, maxdepth= 12, xval =10, cp = 0),
            data = trainset)

rpart.plot(dt)
```



```{r}
# 
pred <- predict(dt, subset(testset, select = -Sales), method = 'anova')
plot(predict(dt, newdata = subset(testset, select = -Sales)), testset$Sales)
RMSE(pred = pred, obs = testset$Sales)
```

```{r}

start_time <- Sys.time()
end_time <- Sys.time()
time <- end_time-start_time
time

```