---
title: "EDA"
author: "Han Wang"
date: "2023-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(lubridate)

data <- read_excel('online_retail.xlsx')
summary(data)
```

```{r}
data %>% is.na %>% colSums
```

There are many NAs in the column CustomerID. Since this column is irrelavent to our analysis, we can simply remove it.

### Data Cleaning

```{r}
# remove free orders
data <- data %>%
  filter(UnitPrice != 0)

# remove column CustomerID
data <- data %>% select(-c(CustomerID))
summary(data)
```
### Data pre-processing
```{r}
# Transform description and country as factor
data <- data %>% mutate(Description = as.factor(Description),
                        Country = as.factor(Country))

# datetime processing
data$date <- format(data$InvoiceDate, "%m/%d/%Y")
data$month <- format(data$InvoiceDate, "%B")
data$week <- format(data$InvoiceDate, "%A")
data$time <- format(data$InvoiceDate, "%H")

# sales
data$Sales <- data$Quantity*data$UnitPrice

head(data)
```
```{r}
# calculating the total sales by month 
data2 <- data %>%
  group_by(month)%>%
  summarise(Sales=sum(Sales))%>%
  arrange(match(month, month.name))

#Line plot
ggplot(data=data2,aes(x=ordered(month, month.name), y=Sales, group =1))+ggtitle("Total Sales by Month ")+
  geom_line(color = "maroon", size = 1.2)+
  geom_point(color="darkblue")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),plot.title = element_text(hjust=0.5, lineheight = 0.8, face = "bold"))+
  ylab("Total Sales") + xlab("Months of the Year")

```
